name: social-bandit
channels:
  - conda-forge
  - defaults
  - plotly
dependencies: 
  - python
  - ipython
  - cython
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn  
  - ipykernel
  - pip
  - plotly
  - fastparquet
  - xarray 
  - dask 
  - netCDF4 
  - bottleneck
  - h5netcdf
  - h5py
  - tqdm
  - networkx
  - pip:
    - autoslot
    - igraph
    - ipywidgets
    - ipympl
    - dash
    - pyyaml 
